/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 juegomapa55.glb --transform 
Files: juegomapa55.glb [7.79MB] > C:\Users\ignac\Escritorio\Trabajos\poliamor2_2\models\juegomapa55-transformed.glb [900.43KB] (88%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/juegomapa55-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[833.244, 51.435, 943.978]} rotation={[-1.457, 0, 0]} scale={[16.541, 28.806, 16.541]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone003} />
          <primitive object={nodes.Bone005} />
          <primitive object={nodes.Bone009} />
          <skinnedMesh name="Cone003" geometry={nodes.Cone003.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cone003.skeleton} />
          <skinnedMesh name="Cone004" geometry={nodes.Cone004.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cone004.skeleton} />
          <skinnedMesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Cube011.skeleton} />
          <skinnedMesh name="Sphere009" geometry={nodes.Sphere009.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Sphere009.skeleton} />
          <skinnedMesh name="Sphere010" geometry={nodes.Sphere010.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Sphere010.skeleton} />
          <skinnedMesh name="Sphere011" geometry={nodes.Sphere011.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Sphere011.skeleton} />
          <skinnedMesh name="Sphere012" geometry={nodes.Sphere012.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Sphere012.skeleton} />
        </group>
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials.PaletteMaterial001} position={[447.906, 63.454, 42.618]} scale={[4.344, 6.566, 0.349]} />
        <mesh name="Cube005" geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[451.935, 63.606, 26.332]} rotation={[-Math.PI, 1.53, -Math.PI]} scale={[17.052, 6.566, 0.353]} />
        <mesh name="Cone" geometry={nodes.Cone.geometry} material={materials['Material.024']} position={[443.236, 101.378, 20.736]} rotation={[-2.353, 0, 0]} scale={9.174} />
        <mesh name="images" geometry={nodes.images.geometry} material={materials.images} position={[-2528.504, 80.756, 303.679]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5477.612} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.026']} position={[448.42, 58.889, -11.736]} scale={39.964} />
        <mesh name="images005" geometry={nodes.images005.geometry} material={materials.PaletteMaterial002} position={[1184.216, -2534.704, 303.679]} rotation={[-2.006, 1.525, 2.007]} scale={[5479.235, 5485.087, 8848.419]} />
        <mesh name="Cone002" geometry={nodes.Cone002.geometry} material={materials['Material.027']} position={[624.207, 180.466, -172.666]} scale={191.01} />
        <mesh name="Sphere001" geometry={nodes.Sphere001.geometry} material={materials['Material.028']} position={[680.679, 84.083, 54.616]} scale={13.965} />
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.PaletteMaterial003} position={[630.017, 137.032, -168.705]} scale={[111.366, 26.87, 106.251]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.031']} position={[666.491, 48.337, 71.609]} scale={[352.258, 5.472, 109.406]} />
        <mesh name="New_Project" geometry={nodes.New_Project.geometry} material={materials['New Project']} position={[525.31, 81.755, 42.895]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.155} />
        <mesh name="Cylinder020" geometry={nodes.Cylinder020.geometry} material={materials.PaletteMaterial001} position={[570.656, 65.778, 88.225]} rotation={[0, 0.328, 0]} scale={[3.588, 10.924, 3.588]} />
        <mesh name="Cylinder023" geometry={nodes.Cylinder023.geometry} material={materials.PaletteMaterial001} position={[570.656, 65.778, 88.225]} rotation={[0, 0.328, 0]} scale={[3.588, 10.924, 3.588]} />
        <mesh name="Cylinder024" geometry={nodes.Cylinder024.geometry} material={materials.PaletteMaterial001} position={[570.656, 65.778, 88.225]} rotation={[0, 0.328, 0]} scale={[3.588, 10.924, 3.588]} />
        <mesh name="Cylinder028" geometry={nodes.Cylinder028.geometry} material={materials.PaletteMaterial001} position={[484.898, 69.336, 312.578]} rotation={[0.225, 0, 0]} scale={[4.206, 12.807, 4.206]} />
        <mesh name="Cylinder018" geometry={nodes.Cylinder018.geometry} material={materials.PaletteMaterial001} position={[523.578, 65.695, 186.757]} rotation={[0.074, -0.344, 0.193]} scale={[3.008, 9.159, 3.008]} />
        <mesh name="Cylinder019" geometry={nodes.Cylinder019.geometry} material={materials.PaletteMaterial001} position={[571.566, 64.947, 20.316]} rotation={[0.189, -0.06, 0.131]} scale={[3.008, 9.159, 3.008]} />
        <mesh name="Cylinder021" geometry={nodes.Cylinder021.geometry} material={materials.PaletteMaterial001} position={[201.52, 53.168, 614.11]} rotation={[0.027, -0.537, 0.006]} scale={[12.641, 38.491, 12.641]} />
        <mesh name="Cylinder022" geometry={nodes.Cylinder022.geometry} material={materials.PaletteMaterial001} position={[523.578, 65.695, 186.757]} rotation={[0.074, -0.344, 0.193]} scale={[3.008, 9.159, 3.008]} />
        <mesh name="Cylinder025" geometry={nodes.Cylinder025.geometry} material={materials.PaletteMaterial001} position={[449.762, 42.841, 427.888]} rotation={[0.074, -0.727, -0.148]} scale={[3.527, 10.738, 3.527]} />
        <mesh name="Cylinder026" geometry={nodes.Cylinder026.geometry} material={materials.PaletteMaterial001} position={[374.701, 36.66, 463.519]} rotation={[0.149, -0.611, -0.101]} scale={[4.542, 13.83, 4.542]} />
        <mesh name="Cylinder027" geometry={nodes.Cylinder027.geometry} material={materials.PaletteMaterial001} position={[469.379, 55.065, 358.398]} rotation={[0.287, -0.325, -0.069]} scale={[3.978, 12.114, 3.978]} />
        <mesh name="Sphere016" geometry={nodes.Sphere016.geometry} material={materials['Material.028']} position={[570.399, 84.083, 88.731]} rotation={[0, 0.328, 0]} scale={13.965} />
        <mesh name="Sphere019" geometry={nodes.Sphere019.geometry} material={materials['Material.028']} position={[570.399, 84.083, 88.731]} rotation={[0, 0.328, 0]} scale={13.965} />
        <mesh name="Sphere020" geometry={nodes.Sphere020.geometry} material={materials['Material.028']} position={[570.399, 84.083, 88.731]} rotation={[0, 0.328, 0]} scale={13.965} />
        <mesh name="Sphere024" geometry={nodes.Sphere024.geometry} material={materials['Material.028']} position={[484.423, 90.151, 317.829]} rotation={[0.225, 0, 0]} scale={16.373} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[905.031, 113.231, 73.645]} scale={[7.294, 68.405, 102.112]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.003']} position={[905.031, 113.231, 73.645]} scale={[7.294, 68.405, 102.112]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Material.010']} position={[-92.839, -6.89, 671.505]} scale={65.466} />
        <mesh name="Cylinder015" geometry={nodes.Cylinder015.geometry} material={materials.PaletteMaterial001} position={[102.559, 94.03, 95.816]} rotation={[0, 0, 1.017]} scale={[0.524, 15.042, 0.524]} />
        <mesh name="Cylinder016" geometry={nodes.Cylinder016.geometry} material={materials.PaletteMaterial001} position={[102.559, 94.03, 95.816]} rotation={[0, 0, 1.017]} scale={[0.524, 15.042, 0.524]} />
        <mesh name="Sphere013" geometry={nodes.Sphere013.geometry} material={materials.PaletteMaterial001} position={[102.559, 94.03, 95.816]} rotation={[0, 0, 1.017]} scale={[4.33, 4.105, 7.398]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials['Material.003']} position={[-420.368, 50.062, 382.378]} rotation={[2.48, -1.352, -0.94]} scale={[-7.294, -68.405, -102.112]} />
        <mesh name="Cylinder017" geometry={nodes.Cylinder017.geometry} material={materials.PaletteMaterial002} position={[901.534, 40.395, 95.816]} scale={[73.063, 6.707, 73.063]} />
        <mesh name="Sphere014" geometry={nodes.Sphere014.geometry} material={materials['Material.028']} position={[521.036, 80.846, 185.266]} rotation={[2.856, -1.321, 3.032]} scale={12.424} />
        <mesh name="Sphere018" geometry={nodes.Sphere018.geometry} material={materials['Material.028']} position={[521.036, 80.846, 185.266]} rotation={[2.856, -1.321, 3.032]} scale={12.424} />
        <mesh name="Sphere021" geometry={nodes.Sphere021.geometry} material={materials['Material.028']} position={[452.7, 60.639, 429.311]} rotation={[-2.648, -0.913, -2.6]} scale={14.566} />
        <mesh name="Sphere015" geometry={nodes.Sphere015.geometry} material={materials['Material.028']} position={[569.331, 80.176, 21.457]} rotation={[0.189, -0.06, 0.131]} scale={12.424} />
        <mesh name="Sphere017" geometry={nodes.Sphere017.geometry} material={materials['Material.028']} position={[203.41, 117.816, 609.15]} rotation={[0.215, 0.799, -0.098]} scale={52.214} />
        <mesh name="Sphere022" geometry={nodes.Sphere022.geometry} material={materials['Material.028']} position={[377.581, 59.651, 466.027]} rotation={[0.46, 0.706, -0.192]} scale={18.76} />
        <mesh name="Sphere025" geometry={nodes.Sphere025.geometry} material={materials['Material.028']} position={[558.119, 45.639, 271.001]} rotation={[0.89, 1.121, -0.72]} scale={[47.451, 28.589, 49.08]} />
        <mesh name="Sphere023" geometry={nodes.Sphere023.geometry} material={materials['Material.028']} position={[470.953, 75.001, 362.499]} rotation={[-0.167, -1.121, 0.663]} scale={16.433} />
        <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials.PaletteMaterial002} morphTargetDictionary={nodes.Plane001.morphTargetDictionary} morphTargetInfluences={nodes.Plane001.morphTargetInfluences} position={[889.883, 103.186, 98.432]} rotation={[0, 0, 1.605]} scale={[48.735, 19.14, 19.079]} />
      </group>
    </group>
  )
}

useGLTF.preload('/juegomapa55-transformed.glb')
