/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 juegomapa2.glb --transform 
Files: juegomapa2.glb [32.18MB] > C:\Users\ignac\Escritorio\Trabajos\poliamor2_2\models\juegomapa2-transformed.glb [2.39MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/juegomapa2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.015']} position={[447.906, 63.454, 42.618]} scale={[4.344, 6.566, 0.349]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[451.935, 63.606, 26.332]} rotation={[-Math.PI, 1.53, -Math.PI]} scale={[17.052, 6.566, 0.353]} />
      <mesh geometry={nodes.Cone.geometry} material={materials['Material.024']} position={[443.236, 101.378, 20.736]} rotation={[-2.353, 0, 0]} scale={9.174} />
      <mesh geometry={nodes.Cone001.geometry} material={materials['Material.025']} position={[443.236, 101.378, 20.736]} rotation={[-2.353, 0, 0]} scale={9.174} />
      <mesh geometry={nodes.images.geometry} material={materials.images} position={[-2528.504, 80.756, 303.679]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={5477.612} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.026']} position={[448.42, 58.889, -11.736]} scale={39.964} />
      <mesh geometry={nodes.Cone002.geometry} material={materials['Material.027']} position={[624.207, 180.466, -172.666]} scale={191.01} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.028']} position={[680.679, 84.083, 54.616]} scale={13.965} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['Material.029']} position={[889.883, 103.186, 98.432]} rotation={[0, 0, 1.605]} scale={[48.735, 19.14, 19.079]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.030']} position={[630.017, 137.032, -168.705]} scale={[111.366, 26.87, 106.251]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.031']} position={[666.491, 48.337, 71.609]} scale={[352.258, 5.472, 109.406]} />
      <mesh geometry={nodes.New_Project.geometry} material={materials['New Project']} position={[525.31, 81.755, 42.895]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.155} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.032']} position={[1158.281, 414.063, 297.465]} scale={16.601} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[905.031, 113.231, 73.645]} scale={[7.294, 68.405, 102.112]} />
    </group>
  )
}

useGLTF.preload('/juegomapa2-transformed.glb')
